#!/bin/bash
# organize files by extension, e.g. [mp4] - folder 
# by defpy (defpy@jabber.org)

IFS=$'\t\n'
ACT=$1
EXTENSIONS=/tmp/extension$$
UNDOFOLDER=/tmp/undofolder$$
FILTER=/tmp/extension-tmp$$
organize_them()
{
filext=( )
INPUT=$1
FILES=$(ls -p | grep -v / | grep "[.]" | cut -d . -f $INPUT | tr A-Z a-z | tr -cs 'a-zA-Z0-9' '[\n*]' )
echo "$FILES" > $EXTENSIONS
echo "" > $FILTER

while read i; do
	if [ "$(echo $i | wc -c )" -lt "9" ]; then
		echo "$i"
		txtconf -a $i $FILTER
	else
		echo "NG $i"
	fi
done < $EXTENSIONS

while read item; do
	LIST=$(ls -p | grep -v / | grep -i "[.]${item}$")
	if [ "$LIST" != "" ];then
		dname="[type] $item"
		if [ -d "$dname" ]; then
			mv $LIST $dname
		else
			mkdir $dname && mv $LIST $dname || echo "Could not create directory"
		fi
	fi
done < $FILTER
rm $FILTER
rm $EXTENSIONS
}

undo_organize()
{
	FOLDER=$(ls | grep "[[type]]")
	echo "$FOLDER" > $UNDOFOLDER
	echo "" >> $UNDOFOLDER
	while read i; do
		if [ -d "$i" ];then
			mv "$i"/* ./ && rm -r $i
		fi
	done < $UNDOFOLDER
	rm $UNDOFOLDER
}

move_one_dir_up()
{

	if [ "$(echo $PWD | grep "/home/")" == "" ];then 
		echo "not home dir"
		exit 1; 
	fi
	FOLDER=$(ls -d */ | grep -v "[[type]]")
	echo "$FOLDER" > $UNDOFOLDER
	echo "" >> $UNDOFOLDER
	while read i; do
		if [ -d "$i" ];then
			mv "$i"/* ./ && rm -r $i
		fi
	done < $UNDOFOLDER
	rm $UNDOFOLDER
}

if [ "$ACT" == "-do" ]; then
	NUMBER="2 3 4 5 6 7"
	for i in $NUMBER;do
		organize_them $i
	done
elif [ "$ACT" == "-undo" ]; then
	undo_organize
elif [ "$ACT" == "-moveup" ]; then
	move_one_dir_up
else
	echo
	echo "organize-folder: move files to different folders ordered by their extensions"
	echo
	echo "([type] extension) e.g. [type] zip, [type] mp4 "
	echo
	echo "options available: -do, -undo, -moveup"
	echo "    -do ( move files to folders ordered by extensions: [type] extension )"
	echo "    -undo ( move files up from folders with the pattern: [type] extension )"
	echo "    -moveup ( move files up from all folders WITHOUT the pattern: [type] extension )"
	exit 0;
fi
