#! /bin/bash
#
# GoPlayer installer
# by defpy  (defpy@jabber.org)
# requires ffmpeg (ffplay) mpg321 youtube-dl gtkdialog zenity (to be replaced)

echo "Installing GoPlayer"
cp ./goplayer /usr/local/bin && echo "bin ok"
cp ./goplay.png /usr/share/icons && echo "image ok"

echo "[Desktop Entry]" > /usr/share/applications/GoPlayer.desktop
echo "Version=0.3" >> /usr/share/applications/GoPlayer.desktop
echo "Name=GoPlayer" >> /usr/share/applications/GoPlayer.desktop
echo "Comment=Simple media player that relies on mpg321 for mp3, ffplay for video files and youtube-dl dor youtube download" >> /usr/share/applications/GoPlayer.desktop
echo "Exec=goplayer" >> /usr/share/applications/GoPlayer.desktop
echo "Icon=/usr/share/icons/goplay.png" >> /usr/share/applications/GoPlayer.desktop
echo "Terminal=false" >> /usr/share/applications/GoPlayer.desktop
echo "Type=Application" >> /usr/share/applications/GoPlayer.desktop
echo "Categories=AudioVideo;Player;" >> /usr/share/applications/GoPlayer.desktop
echo "MimeType=video/mpeg;video/x-mpeg;video/x-avi;video/x-ms-asf;video/x-ms-wmv;video/x-msvideo;application/x-matroska;audio/x-mp3;audio/mp4;video/mp4;video/x-flv;" >> /usr/share/applications/GoPlayer.desktop

cp /usr/share/applications/GoPlayer.desktop ${HOME}/Desktop && echo "shortcut ok"
chmod a+w ${HOME}/Desktop/GoPlayer.desktop && echo "permissions ok"
echo "Finished installing"

