#!/bin/bash
# osxmb - gui to shutdown, reboot and set ps3 to boot to xmb next time it boots
# by defpy (defpy@jabber.org)
cp /usr/share/icons/joy.png /tmp
cp /usr/share/icons/reboot.png /tmp
cp /usr/share/icons/shutdown.png /tmp

export xmb='<window window_position="1"  decorated="false" title="Exit" icon_name="gtk-quit" resizable="false">
   <vbox>
   <hbox>
    <button tooltip-text="Shutdown and boot XMB next time"><input file>/tmp/joy.png</input>
	<action>ps3-flash-util -b; halt &</action>
	</button>
	<button tooltip-text="Reboot to XMB"><input file>/tmp/reboot.png</input>
	<action>ps3-boot-game-os &</action>
	</button>
	<button tooltip-text="Shutdown PS3"><input file>/tmp/shutdown.png</input>
	<action>halt &</action>
	</button>
	 </hbox>
  <text>
    <label>Exit Ubuntu</label>
  </text>
  <button cancel></button>
    </vbox>
   <action signal="hide">exit:Exit</action> 
</window>'

gtkdialog --program=xmb



